import os

# CONFIGURATION VARIABLE
MINIFILEBOX_CHUNK_SIZE = 50000000
MINIFILEBOX_BASE_URI = '/minifilebox/api/v1'
MINIFILEBOX_STORAGE_TYPE = 'cassandra'
MINIFILEBOX_CASSANDRA_CLUSTER=os.environ.get('MINIFILEBOX_CASSANDRA_CLUSTER', '127.0.0.1').split(',')
MINIFILEBOX_CASSANDRA_OBJECT_KEY_SPACE = 'minifilebox_objects'
MINIFILEBOX_CASSANDRA_CONTEXT_KEY_SPACE = 'minifilebox_context'
MINIFILEBOX_CASSANDRA_REPLICATION_FACTOR = 2
