import os

# CONFIGURATION VARIABLE
MINIFILEBOX_CHUNK_SIZE = 500
MINIFILEBOX_BASE_URI = '/minifilebox/api/v1'
MINIFILEBOX_STORAGE_TYPE = 'remote'


# REMOTE FILE STORAGE CONFIGURATION
MINIFILEBOX_CONTEXTSTORE_ENDPOINT = os.environ.get('MINIFILEBOX_CONTEXTSTORE_ENDPOINT',
                                                   'http://0.0.0.0:5002%s/context' % MINIFILEBOX_BASE_URI)
MINIFILEBOX_OBJECTSTORE_ENDPOINT = os.environ.get('MINIFILEBOX_OBJECTSTORE_ENDPOINT',
                                                  'http://0.0.0.0:5001%s/objects' % MINIFILEBOX_BASE_URI)
