import os

# CONFIGURATION VARIABLE
MINIFILEBOX_CHUNK_SIZE = 500
MINIFILEBOX_BASE_URI = '/minifilebox/api/v1'
MINIFILEBOX_STORAGE_TYPE = 'memory'

# CASSANDRA FILE STORAGE CONFIGURATION
MINIFILEBOX_CASSANDRA_CLUSTER = os.environ.get('MINIFILEBOX_CASSANDRA_CLUSTER', '172.17.0.2').split(',')
MINIFILEBOX_CASSANDRA_OBJECT_KEY_SPACE = 'minifilebox_objects'
MINIFILEBOX_CASSANDRA_CONTEXT_KEY_SPACE = 'minifilebox_context'
MINIFILEBOX_CASSANDRA_REPLICATION_FACTOR = 1

# REMOTE FILE STORAGE CONFIGURATION
MINIFILEBOX_CONTEXSTORE_HOST = os.environ.get('MINIFILEBOX_CONTEXTSTORE_HOST')
MINIFILEBOX_OBJECTSTORE_HOST = os.environ.get('MINIFILEBOX_OBJECTSTORE_HOST')
